version: 2.1
executors:
  dev-api:
    docker:
      - image: cimg/openjdk:8.0.312
      - image: postgres
        auth:
          username: amesika
          password:  $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: acehome
          POSTGRES_PASSWORD: password
          POSTGRES_DB: acehome-db

orbs:
  maven: circleci/maven@1.2.0

jobs:
  use-executor:
    executor: dev-api
    steps:
        - checkout
        - run: 
            name: Wait Test db
            command: dockerize -wait tcp://localhost:5432 -timeout 1m
        - run:
            name: Restore Backup
            command: pg_restore -h localhost -p 5432 -d acehome-db -U acehome < ace-home-docker/db/backupTest 
        - run:
            name: Ls
            command: psql  -h localhost -d acehome-db -U acehome Select * from activity;
        - run:
            name: Select
            command: Select * from activity

workflows:
  maven_test:
    jobs:
      - use-executor  
      - maven/test:
          requires: [use-executor]
          executor: dev-api
          app_src_directory: ace-home
          filters:
            branches:
                only:
                    - dev-api