version: 2.1
jobs:
  build:
    working_directory: ~/ace-home
    docker:
      - image: maven:3.5.0-jdk-8
      - image: postgres:9.6.2-alpine
        auth:
          username: amesika
          password:  $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: acehome
          POSTGRES_PASSWORD: password
          POSTGRES_DB: acehome-db
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

workflows:
  maven_test:
    jobs:
      - build:
          filters:
            branches:
                only:
                    - dev-api