version: 2.1
executors:
  dev-api:
    docker:
      - image: cimg/openjdk:8.0.312
      - image: circleci/postgres:9.6-alpine
        auth:
          username: amesika
          password:  $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: acehome
          POSTGRES_PASSWORD: password
          POSTGRES_DB: acehome-db

orbs:
  maven: circleci/maven@1.2.0

jobs:
  use-executor:
    executor: dev-api
    steps:
        - checkout
        - run: 
            name: Wait Test db
            command: dockerize -wait tcp://localhost:5432 -timeout 1m
        - run:
            name: Ls
            command: ls -a ace-home-docker/db
        - run:
            name: Restore Backup
            command: psql -U acehome < ace-home-docker/db/backupTest

workflows:
  maven_test:
    jobs:
      - use-executor  
      - maven/test:
          executor: dev-api
          app_src_directory: ace-home
          filters:
            branches:
                only:
                    - dev-api