orbs:
  maven: circleci/maven@x.y
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: ace-home
          filters:
            branches:
                only:
                    - dev-api