executors:
  dev-api:
    docker:
      - image: 'cimg/openjdk:11.0'
      - image: circleci/postgres:9.6-alpine
        auth:
          username: amesika
          password:  $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: acehome
          POSTGRES_PASSWORD: password
          POSTGRES_DB: acehome-db
orbs:
  maven: circleci/maven@1.2.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: dev-api
          app_src_directory: ace-home
          filters:
            branches:
                only:
                    - dev-api