version: 3

services:

  # Data base 
  db:
    image: postgres
    networks:
      - backend
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: acehome
      POSTGRES_PASSWORD: password
    volumes:
      - ah_pgsql:/var/lib/postgresql
      - ah_pgsql_data:/var/lib/postgresql/data

  # Quality Code
  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - db_sonar
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db_sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

db_sonar:
    image: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - snr_pgsql:/var/lib/postgresql
      - snr_pgsql_data:/var/lib/postgresql/data

networks:
  backend:
  frontend:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  snr_pgsql:
  snr_pgsql_data:
  ah_pgsql:
  ah_pgsql_data: